#!/usr/bin/env python3
import sys


def solve(N: int, S: str):
    # 全体における最大のダンゴレベル
    L = 0
    # 部分ダンゴ文字列におけるダンゴレベル
    l = 0
    for s in S:
        if s == 'o':
            l += 1
        else:
            L = max(L, l)
            l = 0
    else:
        L = max(L, l)

    if '-' in S:
        print(L if L else -1)
    else:
        print(-1)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
