#!/usr/bin/env python3
import sys

# x について x^3 + x と N の大小関係を調べる
# ただし、相対誤差または絶対誤差は 0.001 未満とする
def check(N: int, x: float):
    diff = x ** 3 + x - N
    if abs(diff) < 0.001:
        return 0
    elif diff > 0:
        return 1
    else:
        return -1

def solve(N: int):
    # 二分探索で x^3 + x = N を満たす最小の x を求める
    # 二分探索の終了条件は、check(N, x) が True となる最小の x が見つかったとき
    left = 0
    right = 10 ** 3 + 1
    mid = (left + right) / 2
    while (sign := check(N, mid)) != 0:
        if sign == 1:
            right = mid
        else:
            left = mid
        mid = (left + right) / 2

    # print(left, mid, right)
    print(mid)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
